/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlCoBan;

/**
 *
 * @author Admin
 */
public class GiaoDienChinh_DieuKhienCoBan extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh_DieuKhienCoBan
     */
    public GiaoDienChinh_DieuKhienCoBan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnPTB2 = new javax.swing.JButton();
        jbtnCheckBoxDemo = new javax.swing.JButton();
        jbtnTextFieldDemo = new javax.swing.JButton();
        jbtnRaDioDemo = new javax.swing.JButton();
        jbtnCombo = new javax.swing.JButton();
        jbtnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPTB2.setText("PTB2");
        jbtnPTB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPTB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPTB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 5, -1, -1));

        jbtnCheckBoxDemo.setText("CheckBoxDemo");
        jbtnCheckBoxDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheckBoxDemoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCheckBoxDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, -1, -1));

        jbtnTextFieldDemo.setText("TextFileld Demo");
        getContentPane().add(jbtnTextFieldDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 5, -1, -1));

        jbtnRaDioDemo.setText("Radio demo");
        getContentPane().add(jbtnRaDioDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 33, -1, -1));

        jbtnCombo.setText("ComBo demo");
        jbtnCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComboActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 33, -1, -1));

        jbtnThoat.setText("Thoat");
        jbtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 33, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPTB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPTB2ActionPerformed
        // TODO add your handling code here:
        new PhuongTrinhBac2().setVisible(true);       
    }//GEN-LAST:event_jbtnPTB2ActionPerformed

    private void jbtnCheckBoxDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheckBoxDemoActionPerformed
        // TODO add your handling code here:
        new CheckBoxDemo().setVisible(true);
    }//GEN-LAST:event_jbtnCheckBoxDemoActionPerformed

    private void jbtnComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComboActionPerformed
        // TODO add your handling code here:
        new ComBoDemo().setVisible(true);
    }//GEN-LAST:event_jbtnComboActionPerformed

    private void jbtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_DieuKhienCoBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_DieuKhienCoBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_DieuKhienCoBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh_DieuKhienCoBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh_DieuKhienCoBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCheckBoxDemo;
    private javax.swing.JButton jbtnCombo;
    private javax.swing.JButton jbtnPTB2;
    private javax.swing.JButton jbtnRaDioDemo;
    private javax.swing.JButton jbtnTextFieldDemo;
    private javax.swing.JButton jbtnThoat;
    // End of variables declaration//GEN-END:variables
}
